### ISSUE TITLE
CSS not in the dist folder

### ISSUE THREAD

**Issue by abdelhakim-atmani** [mhnpd/react-loader-spinner#12]
Hi,

Thanks for your work very nice and easy to use.

When I try to use the Loader I received this error message:
./node_modules/react-loader-spinner/dist/loader/CradleLoader.js
Module not found: Can't resolve './css/CradleLoader.css' in '$myappfolder/node_modules/react-loader-spinner/dist/loader'

When I add the css folder from src to dist everything works.

**Comment by mhnpd** [comment]
https://github.com/mhnpd/react-loader-spinner/commit/3731d4af78dc6ea109148767669713b5f12bb765 fixed #13

**Comment by DrEhsan** [comment]
still i have this issue : 
error: bundling failed: Error: Unable to resolve module `./css/CradleLoader.css`

**Comment by fantypants** [comment]
I'm not sure if this is the issue, but i'm playing around changing line 2 of CradleLoader.js and Triangle.js to:

```  if (typeof define === "function" && define.and``` from ```  if (typeof define === "function" && define.amd```
