### ISSUE TITLE
CSS bleed in Triangle.css

### ISSUE THREAD

**Issue by isaackeyet** [mhnpd/react-loader-spinner#14]
Problem: CSS bleeds through to any other part of the app, not limited to the spinners themselves

Suggestion: add a parent class for each spinner (svg) and base all CSS rules on this.

solution for triangle.css, but the classes are fairly ambiguous in other css files as well:
```
svg.loader-spinner {
  -webkit-transform-origin: 50% 65%;
          transform-origin: 50% 65%;
}

svg.loader-spinner polygon {
  stroke-dasharray: 17;
  -webkit-animation: dash 2.5s cubic-bezier(0.35, 0.04, 0.63, 0.95) infinite;
          animation: dash 2.5s cubic-bezier(0.35, 0.04, 0.63, 0.95) infinite;
}

@-webkit-keyframes loader-spinner-dash {
  to {
    stroke-dashoffset: 136;
  }
}

@keyframes loader-spinner-dash {
  to {
    stroke-dashoffset: 136;
  }
}
@-webkit-keyframes loader-spinner-rotate {
  100% {
    -webkit-transform: rotate(360deg);
            transform: rotate(360deg);
  }
}
@keyframes loader-spinner-rotate {
  100% {
    -webkit-transform: rotate(360deg);
            transform: rotate(360deg);
  }
}
```

**Comment by Ev-Abbott** [comment]
Seconding this. Was using this module in my application and it caused unrelated SVGs to start spinning. Needless to say it was a surprising bug to find.

**Comment by mhnpd** [comment]
@isaackeyet Applying css on svg tag is causing this issue. New version should solve this one.
