### ISSUE TITLE
unmet peer dependency

### ISSUE THREAD

**Issue by baitun** [mhnpd/react-loader-spinner#15]
Every time when I run `yarn install`, it says:
```
warning " > react-loader-spinner@2.1.0" has unmet peer dependency "prop-types@^15.6.1".
```
How to fix this?

**Comment by mhnpd** [comment]
@baitun npm no longer installs peer dependencies so you need to install them manually, just do an npm install on the needed deps, and then try to install the main one again. UNMET PEER DEPENDENCY error is thrown when the dependencies of one or more modules specified in the package.json file is not met.
