### ISSUE TITLE
Applying class

### ISSUE THREAD

**Issue by modestotech** [mhnpd/react-loader-spinner#16]
I want to center the svg by passing in a className in react. Is this supported as a prop? I can't get it to work.

**Comment by mhnpd** [comment]
Added style props. 
```
<Loader style ={style object } 
```

**Comment by to-sh-1** [comment]
It seemed like you connected style to classname.  Its fine, except now I'm getting errors on my tests because of the proptype validations

**Comment by epexa** [comment]
I'm also getting a warning:
**Warning: Failed prop type: Invalid prop `style` of type `string` supplied to `Loader`, expected `object`.**
```js
<Loader type='Watch' color='#00BFFF' height={ 27 } width={ 27 } style={ 'spinner' } />
```

**Comment by karimkkanji** [comment]
I found out using:
`<Loader wrapperStyle ={style object }/> `
works for me.

This hasn't worked for me:
https://github.com/mhnpd/react-loader-spinner/issues/16#issuecomment-435758348
