### ISSUE TITLE
Grid Loader Animation Issue

### ISSUE THREAD

**Issue by jakebott** [mhnpd/react-loader-spinner#19]
The top-left dot in the Grid loader does not animate due to a typo - In [src/loader/Grid.js](https://github.com/mhnpd/react-loader-spinner/blob/master/src/loader/Grid.js#L7) on line 7
`attributeName="fillOpacity"` should read `attributeName="fill-opacity"`.

**Comment by mhnpd** [comment]
@jakebott Thankyou for pointing out. Solves in 2.3.0. Closing this issue
