### ISSUE TITLE
Invalid DOM property `fill-opacity`. Did you mean `fillOpacity`

### ISSUE THREAD

**Issue by mohamed-alashry** [mhnpd/react-loader-spinner#2]
I used hearts as the loader type but a warning is shown in console:

> Warning: Invalid DOM property `fill-opacity`. Did you mean `fillOpacity`?

**Comment by MikeLindenau** [comment]
just ran into this... any thoughts?

**Comment by mhnpd** [comment]
Yep this is react warning for naming convension. Fixing soon

**Comment by tommyalvarez** [comment]
@mhnpd Dont forget about this :)
