### ISSUE TITLE
CSS pollutes global namespace

### ISSUE THREAD

**Issue by ukch** [mhnpd/react-loader-spinner#20]
To reproduce:
* Have a site that contains one of the loader spinners. I am using Gatsby but I am fairly confident this issue will occur in all configurations.
* Elsewhere in the site, insert code like the following: `<div className="shadow">content</div>`
* Inspect the generated content in the browser

Expected: The `.shadow` div should be unstyled

Actual: The `.shadow` div contains the following styling:
```css
.shadow {
	clear: left;
	padding-top: 1.5em;
}
```
This CSS is specific to the `Loader` component and should be namespaced as such, e.g. `.react-loader-spinner--shadow`.

**Comment by ukch** [comment]
Oops, I've just seen #14 and think this issue may be a duplicate. Let me get the upgraded version and check...

**Comment by ukch** [comment]
I have upgraded to version 2.2.0 and I can confirm the issue still persists. The problem file is `CradleLoader.css`.

**Comment by mhnpd** [comment]
@ukch Thanks for pointing out. All the classes that could pollute global namespace was replace with prefix of package name. Version 2.3.0 is publish. Closing this issue.
