### ISSUE TITLE
Not working in IE.

### ISSUE THREAD

**Issue by narendrakumarmyilsamy** [mhnpd/react-loader-spinner#21]
Loader animation is not working in IE11.

**Comment by willhausman** [comment]
Animation also does not work in Edge.

**Comment by nimesha95** [comment]
Did anyone find any workarounds for this issue?

**Comment by ezzkht** [comment]
The animation is frozen in MS Edge browser

**Comment by mhnpd** [comment]
Refer a bug on EDGE:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/3723601/

**Comment by pedrofs** [comment]
I'm using it on production and I see this error for IE on my logs:
```
83   var componentNames = ["Audio", "BallTriangle", "Bars", "Circles", ... ];
84  
85   function componentName(type) {
86    if (componentNames.includes(type)) {
87      return _loader.Spinner[type];
88    }
```
**undefined is not a function on line 86**

Includes is not supported on IE: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes

In the link above there is a workaround using a func declaration to polyfill includes.
