### ISSUE TITLE
High CPU usage when using some spinners in the page

### ISSUE THREAD

**Issue by moish83** [mhnpd/react-loader-spinner#23]
I have a dashboard page, which has several charts displayed on it.
I used a lazy renderer which uses the react-loader-spinner as the component displayed before the chart is displayed.
When entering the page, the CPU usage of the browser (Firefox, Safari, Chrome) is reaching 100%.
Even on your demo page, with only one spinner showing on the screen without anything else, the CPU is at constant 25-30% CPU usage.

**Comment by benjaminsuch** [comment]
Can confirm. It also takes ~40% GPU power for me.

**Comment by mhnpd** [comment]
Closes #23
