### ISSUE TITLE
Add property to let a loader know when to render

### ISSUE THREAD

**Issue by blakeyoder** [mhnpd/react-loader-spinner#30]
@mhnpd  - I want to propose an enhancement to the `<Loader />`

**Scenario:** Imagine you have an upload button that makes a `POST` request to a server. In flight, the React state is set to `loading = true;` which triggers the `<Loader />` to render. This works great and as expected. Now, let's say you also have a delete button that deletes a resource on the server. This delete button follows the same logic as the upload button. Request is made, state is changed to true, loader renders. In this case, we have two loaders that are relying on the same state variable and thus we get both Loaders rendering even though one action was taken.

**Proposal:** There are a couple of ways to fix this. Currently, I'm maintaining a loading state map that tells the two loaders _when_ to render. This allows me to have N loaders in the same component and render each one individually. However, I think it would be a better developer experience if the `<Loader />` component could take in a prop function that evaluated to `true` or `false` and let the loader know to render or not. There are a couple of ways to accomplish this but the idea is that the `<Loader />` could be enhanced so that it knew _when_ to render. Thoughts? I can put together a PR if you think this is an added value.

**Comment by mhnpd** [comment]
New visible prop was added to show and hide the loader. The visible prop is of type string or boolean. While it as false the component will return null value otherwise return a required component.

Version related to this change: 3.1.2.
This closes #30 .

**Comment by trixn86** [comment]
The documentation says that `visible` defaults to `false` but if not provided the `Loader` is actually visible. Is that the intended behavior?
