### ISSUE TITLE
Typescript type missing!!!

### ISSUE THREAD

**Issue by sathishjobs** [mhnpd/react-loader-spinner#34]
TypeScript error: Could not find a declaration file for module 'react-loader-spinner'. '/Users/sathishjobs/work/work/2i/react/a8/a8flow-web/node_modules/react-loader-spinner/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-loader-spinner` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-loader-spinner';

How do i solve this problem...

**Comment by grrowl** [comment]
put this in a `.d.ts` file somewhere in your app:

```ts
declare module "react-loader-spinner" {
  type Loader = React.Component<{
    color?: string;
    width?: number;
    height?: number;
    type:
      | "Audio"
      | "Ball-Triangle"
      | "Bars"
      | "Circles"
      | "Grid"
      | "Hearts"
      | "Oval"
      | "Puff"
      | "Rings"
      | "TailSpin"
      | "ThreeDots";
  }>;

  export default function(props): Loader;
}
```

**Comment by mortoni** [comment]
any improvement?

**Comment by grrowl** [comment]
You can fix this inside your project using the instructions I posted, or with a bit more effort you can submit the types provided above to https://github.com/DefinitelyTyped, then anyone can `npm install --save-dev @types/react-loader-spinner` and you'll be helping the wider community :)

edit: Not everyone uses TypeScript so I think it's reasonable to put in a bit of effort yourself if you need more than a package that "just works" in Javascript. They already did the hard work of providing a package for you under a permissive licence :)

**Comment by jordantai** [comment]
There is an @types definition now so this can probably be closed.
