### ISSUE TITLE
Add a timeout props

### ISSUE THREAD

**Issue by kingingcole** [mhnpd/react-loader-spinner#43]
When I started using this project, I just needed to simulate a network request or any other time-consuming processes. To do this, I had to set and manipulate states in my component and use timeouts. it would be better if we added a little bit of customization by way of props to this project. 
Hence, I have created one more prop, `timeout`, which should be a number.
I have already forked this project and written an implementation for this. A PR will be opened if I get a go-ahead on this issue.

**Comment by mhnpd** [comment]
@kingingcole Sure can review your implementation.

**Comment by kingingcole** [comment]
Pull request submitted: #44

**Comment by mhnpd** [comment]
Closes #44
