### ISSUE TITLE
Triangle loader is not spinning

### ISSUE THREAD

**Issue by max-zviahintsev** [mhnpd/react-loader-spinner#47]
Triangle loader is not spinning. Ver. 3.1.2

**Comment by michal-majer** [comment]
@Max-Zviagintsev 
Plane also, any ideas?

**Comment by max-zviahintsev** [comment]
I've just downgraded the version to make it work.

**Comment by binbingol** [comment]
@Max-Zviagintsev 

Which version did you downgrade to? Thanks!

**Comment by max-zviahintsev** [comment]
@binbingol Latest 2+ version
