### ISSUE TITLE
Invariant Violation: View config not found for name animate.

### ISSUE THREAD

**Issue by anoopjangra90** [mhnpd/react-loader-spinner#48]
Invariant Violation: View config not found for name animate. Make sure to start component names with a capital letter.

This error is located at:
    in animateTransform (created by Circles)
    in path (created by Circles)
    in svg (created by Circles)
    in Circles (created by Loader)
    in div (created by Loader)
    in Loader (at ProgressView.js:13)

Code : 

<Loader
                type="Circles"
                color="#00BFFF"
                height={100}
                width={100}
                timeout={3000} //3 secs

            />

**Comment by mhnpd** [comment]
@anoopjangra90 Can you post steps to recreate this bugs.

**Comment by bsor-dev** [comment]
Same
