### ISSUE TITLE
Clear timeout when component dismounts 

### ISSUE THREAD

**Issue by scucchiero** [mhnpd/react-loader-spinner#52]
If you dismount a screen using this loader spinner, when the loading timeout occurs, it raises an error because it is trying to dismount the nonexistent component.

`Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in Loader (at AppLoading.js:67)`

**Comment by Ellfish** [comment]
I can confirm the same problem, using version 3.1.4 when setting the timeout option. If I don't set the timeout option, I don't get the error.
