### ISSUE TITLE
None of the spinners work in Edge

### ISSUE THREAD

**Issue by leonbrag** [mhnpd/react-loader-spinner#53]
None of the spinners work in Edge on Windows (all the latest).

Is this by design?

To repro open any demo page in Edge.

**Comment by laradevitt** [comment]
Can confirm. Unfortunately there are no helpful messages in console.

**Comment by stdavis** [comment]
I just loaded https://mhnpd.github.io/react-loader-spinner/ in Edge on Windows and macOS and everything seemed to work fine. This issue might be able to be closed.
![image](https://user-images.githubusercontent.com/1326248/95388747-040a9200-08b0-11eb-9440-b34c848c9b45.png)

**Comment by mhnpd** [comment]
https://weqls.csb.app/

Working from V5.0.5
