### ISSUE TITLE
add string prop type to width and height?

### ISSUE THREAD

**Issue by tylim88** [mhnpd/react-loader-spinner#59]
currently the props type is

```
Loader.propTypes = {
  height: PropTypes.number,
  width: PropTypes.number,
  color: PropTypes.string,
  label: PropTypes.string
};
```

however height and width are able to receive string input, this is convenient if we want to set something like 

`width='3rem' height='3rem'`

it works fine as far as I can see

what is the reason to not include string prop type?

**Comment by mhnpd** [comment]
Version 3.1.8 includes the fix.
