### ISSUE TITLE
className type error

### ISSUE THREAD

**Issue by tylim88** [mhnpd/react-loader-spinner#72]
![image](https://user-images.githubusercontent.com/5227509/89705118-0ffbd580-d98d-11ea-9e32-0b63949cdf3b.png)
type error in className, however class successfully applied

currently I use // @ts-ignore to ignore the error

**Comment by jordantai** [comment]
I've updated the @types definition file on Definitely Typed which should prevent this bug, however, the original creator of the @types needs to review and confirm the PR which they haven't done. I guess that's a flaw with the whole DefinitelyTyped thing.
