### ISSUE TITLE
ThreeDots, Puff, Rings, and Triangle loaders do not work in Safari

### ISSUE THREAD

**Issue by spencer-wegner** [mhnpd/react-loader-spinner#92]
The ThreeDots spinner works fine in Chrome and Firefox (I've checked those) but it doesn't work in Safari.

I'm not sure if this is because of the way Safari interprets SVGs.

**Comment by gulati-ofasi** [comment]
any update on this?

**Comment by spencer-wegner** [comment]
Looking at the [demo page](https://mhnpd.github.io/react-loader-spinner/), in addition to ThreeDots, the Puff, Rings, and Triangle don't work in Safari. The Triangle doesn't appear to work in Chrome either.

**Comment by bgmarc33** [comment]
did some quick looking at ThreeDots, changing attribute name from `attributeName="fillOpacity` to `attributeName="fill-opacity` seemed to do the trick @mhnpd

**Comment by c1oneman** [comment]
Any update on this issue, I am still having it. I do not know what the attributeName change is exactly @bgmarc33

**Comment by bgmarc33** [comment]
> Any update on this issue, I am still having it. I do not know what the attributeName change is exactly @bgmarc33

it's a bug in the code @c1oneman

**Comment by mu-majid** [comment]
Any updates on this issue, or workarounds?

**Comment by riptusk331** [comment]
> Any updates on this issue, or workarounds?

no commits in 7 months and the maintainer doesn't answer any issues. seems like this library has been abandoned for now. just fork it and use @bgmarc33's fix above to build your own library.

**Comment by mu-majid** [comment]
@riptusk331 Thanks, This fix worked, but my issue is actually with Safari now 🥲 , Safari pauses all threads related to animation when a new page is about to be rendered. So using this animation on a form submission button will still not work 😄 .

**Comment by rmanalan** [comment]
I fixed this issue with `Rings` using the following diff:

```diff
diff --git a/node_modules/react-loader-spinner/dist/loader/Rings.js b/node_modules/react-loader-spinner/dist/loader/Rings.js
index 84ff8e8..c485f8b 100644
--- a/node_modules/react-loader-spinner/dist/loader/Rings.js
+++ b/node_modules/react-loader-spinner/dist/loader/Rings.js
@@ -50,32 +50,6 @@ var Rings = function Rings(props) {
     values: "2;0",
     calcMode: "linear",
     repeatCount: "indefinite"
-  })), /*#__PURE__*/_react["default"].createElement("circle", {
-    cx: "22",
-    cy: "22",
-    r: props.radius,
-    strokeOpacity: "0"
-  }, /*#__PURE__*/_react["default"].createElement("animate", {
-    attributeName: "r",
-    begin: "3s",
-    dur: "3s",
-    values: "6;22",
-    calcMode: "linear",
-    repeatCount: "indefinite"
-  }), /*#__PURE__*/_react["default"].createElement("animate", {
-    attributeName: "strokeOpacity",
-    begin: "3s",
-    dur: "3s",
-    values: "1;0",
-    calcMode: "linear",
-    repeatCount: "indefinite"
-  }), /*#__PURE__*/_react["default"].createElement("animate", {
-    attributeName: "strokeWidth",
-    begin: "3s",
-    dur: "3s",
-    values: "2;0",
-    calcMode: "linear",
-    repeatCount: "indefinite"
   })), /*#__PURE__*/_react["default"].createElement("circle", {
     cx: "22",
     cy: "22",
```

The resulting SVG is this:

```
<svg width="80" height="80" viewBox="0 0 45 45" xmlns="http://www.w3.org/2000/svg" stroke="#ffc429" aria-label="audio-loading">
  <g fill="none" fill-rule="evenodd" transform="translate(1 1)" stroke-width="2">
    <circle cx="22" cy="22" r="6" stroke-opacity="0">
      <animate attributeName="r" begin="1.5s" dur="3s" values="6;22" calcMode="linear" repeatCount="indefinite"></animate>
      <animate attributeName="stroke-opacity" begin="1.5s" dur="3s" values="1;0" calcMode="linear" repeatCount="indefinite"></animate>
      <animate attributeName="stroke-width" begin="1.5s" dur="3s" values="2;0" calcMode="linear" repeatCount="indefinite"></animate>
    </circle>
    <!-- <circle cx="22" cy="22" r="6" stroke-opacity="0">
      <animate attributeName="r" begin="3s" dur="3s" values="6;22" calcMode="linear" repeatCount="indefinite"></animate>
      <animate attributeName="strokeOpacity" begin="3s" dur="3s" values="1;0" calcMode="linear" repeatCount="indefinite"></animate>
      <animate attributeName="strokeWidth" begin="3s" dur="3s" values="2;0" calcMode="linear" repeatCount="indefinite"></animate>
    </circle> -->
    <circle cx="22" cy="22" r="8">
      <animate attributeName="r" begin="0s" dur="1.5s" values="6;1;2;3;4;5;6" calcMode="linear" repeatCount="indefinite"></animate>
    </circle>
  </g>
</svg>
```

**Comment by jamesdfrearson** [comment]
In regards to the ThreeDots animation:

I'm unsure if this fix breaks it on other devices, but for iOS Safari this 'fix' works...

Edit the ./node_modules/react-loader-spinner/dist/loader/ThreeDots.js file and replace all instances of "fillOpacity" to "fill-opacity".

@bgmarc33 has already mentioned this but I just wanted to make it clearer for people still struggling, so thank @bgmarc33, not me!
