### ISSUE TITLE
Bundled some Unused Spinner type

### ISSUE THREAD

**Issue by tonchan1216** [mhnpd/react-loader-spinner#95]
This is just my question and report.

I'm using this package with Gatsby and visualized the bundle size. Then I found that JS about the unused Spinner type was also bundled. 

![image](https://user-images.githubusercontent.com/10722536/114296232-2393a900-9ae5-11eb-9fc0-87150081ef88.png)

Is this the specification of this package? Or Is it my misconfiguration?

IF former, when using only one type (like me), and I think it inefficient to load a lot of content.
And, IF it is possible to bundle only the type of assets we use, I would like to improve it!😋

**Comment by Unn4m3DD** [comment]
I'm having the same issue and would gladly implement a solution, should I create a pull request solving the issue? @mhnpd

**Comment by mhnpd** [comment]
For sure

**Comment by mhnpd** [comment]
v5.0.6 solves it.
