### ISSUE TITLE
Loader cannot be used as a JSX component

### ISSUE THREAD

**Issue by Saintenr** [mhnpd/react-loader-spinner#96]
Hi, i got the following error:

![image](https://user-images.githubusercontent.com/33520976/116874075-000ddb00-ac19-11eb-9982-04e35d690d0f.png)
![image](https://user-images.githubusercontent.com/33520976/116874099-0ac87000-ac19-11eb-885d-8831fc88d4b7.png)

any idea?

**Comment by fattynoparents** [comment]
I have the same issue. Any updates on this?

**Comment by Ofer-Gal** [comment]
Same here Using react 16.9 with hooks
I installed @3.1.14 and the error is gone

**Comment by fish-filet** [comment]
Same issue here. Using React 17.0.2, React Loader Spinner version 4.0 with TypeScript. I can't install version 3 of the loader spinner, because React 16.9 is needed

**Comment by chrisc-cy2** [comment]
This happens for me as well with react 17.0.2 and react-loader-spinner 4.0.0.
