### ISSUE TITLE
Pull request for secondaryColor and secondaryStrokeWidth for the oval spinner

### ISSUE THREAD

**Issue by AdrianRisch** [mhnpd/react-loader-spinner#97]
I added a secondaryColor and secondaryStrokeWidth for the oval spinner. I would like to pull request this. You can take a look at my branch here : https://github.com/AdrianRisch/react-loader-spinner/tree/Add-Secondoary-Color-at-Oval

![image](https://user-images.githubusercontent.com/50317883/118969074-f13f5c00-b96c-11eb-8bcd-567e1d4f1d4a.png)
![image](https://user-images.githubusercontent.com/50317883/118969272-277cdb80-b96d-11eb-9bab-918f3e70051b.png)

**Comment by mhnpd** [comment]
V0.5.8 Fixes this
